### ISSUE TITLE
Can't connect to the public server ogmp.net

### ISSUE THREAD

**Issue by EricPlayZ** [ogmp/ogmp_client#10]
Hi! When i try to connect to the public server ogmp.net it doesn't work! Do i put a random Username? And in the address i put ogmp.net?

**Comment by EricPlayZ** [comment]
I am using a cracked version!

**Comment by maxim-fedotov-1997** [comment]
You can't do so with cracked version. Better buy it and be up-to-date. Mod will be updating as new Overgrowth versions roll out. For $29.99, you could ensure you can use it. Cheers!

**Comment by Gyrth** [comment]
Yep.

**Comment by EricPlayZ** [comment]
Oh ok!
