### ISSUE TITLE
Connection made, but no entities are being spawned/synced?

### ISSUE THREAD

**Issue by Sodukene** [ogmp/ogmp_client#13]
I'm not an expert in terms of how multiplayer works, but the instance of the server is indeed working, you can connect to the server and connect in the chat, however, the client isn't loading in any of the entities or any of the characters, as you should say.

Me and my friend bogbean tried to join a server, we get 3 errors, it doesn't stop us from loading the game however.

![](https://i.gyazo.com/74a95a71497f9935818a78e69f2e9441.png)

![](https://i.gyazo.com/73b973cf2232000b42af45d940a35d74.png)

![](https://i.gyazo.com/c2d09441a0ced00815318575f726bc7b.png)

it seems to be an issue related to beta 6? I assume this was working in beta 5? But the new update must of borked it. I don't know how this game compiles scripts, but I think they've updated some kind of function which you haven't included and it's trying to find it? I'm not so sure. I looked in remote_player.as but I couldn't find CheckSpecies().

**Comment by thingscouldbeworse** [comment]
Making this edit: https://github.com/ogmp/ogmp_client/pull/14 
Will fix that first bug and let you join servers without crashing. BrainUpdate() is a function in remote_player.as that won't compile as it references a nonexistent function BrainSpeciesUpdate().
credit to https://github.com/cychow mostly

When actually playing I'm still experiencing desync issues on death, but at least it won't crash now.

**Comment by Gyrth** [comment]
Fixed in 2a9ef932d7bdec3c152c43b643634f3e141ae90d
