### ISSUE TITLE
Overgrowth crashes when joining a map

### ISSUE THREAD

**Issue by ShlickCSGO** [ogmp/ogmp_client#9]
When I install OGMP, it gives me this error when I go into Red Shards: 
![capture](https://cloud.githubusercontent.com/assets/19522146/15457236/3b1e4376-203a-11e6-8cc6-66668e86a74a.PNG)

Any ideas of how to fix?

**Comment by EricPlayZ** [comment]
Well try going into that file, opening it with Notepad++ and put that line of code `void PreDraw()` and try see if it works.

**Comment by ShlickCSGO** [comment]
Dude, this was posted over a year ago. It's fixed now. Thanks for your willingmess to help, though

**Comment by EricPlayZ** [comment]
Eh I know, I just wanted to say it because if u had more troubles like this... just so you know :) And np :)
